<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Formulaire d'ajout d'article</title>
</head>
<body>
    <header>
        <h1>Mon super blog !</h1>
    </header>
    <main>
        <article>
            <h2><?=$article['title'];?></h2>
            <small>Créé le <?=(new DateTimeImmutable($article['createdAt']))->format('d/m/Y');?></small>
            
            <?php if ($article['image']): ?>
                <img src="images/<?=$article['image'];?>" alt="">
            <?php endif; ?>

            <?php if ($article['abstract']): ?>
                <p><?=$article['abstract'];?></p>
            <?php endif; ?>

            <p><?=$article['content'];?></p>
        </article>
    </main>
</body>
</html>