<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Formulaire d'ajout d'article</title>
</head>
<body>
    <header>
        <h1>Mon super blog !</h1>
    </header>
    <main>
        <section>
            <h2>Les derniers articles</h2>
            <?php // foreach ($articles as $article){ ?>
            <?php foreach ($articles as $article): ?>
                <article>
                    <h3><?=$article['title'];?></h3>
                    <small>Créé le <?=(new DateTimeImmutable($article['createdAt']))->format('d/m/Y');?></small>
                    
                    <?php if ($article['image']): ?>
                        <img src="images/<?=$article['image'];?>" alt="">
                    <?php endif; ?>

                    <p><?=$article['abstract']?$article['abstract']:substr($article['content'],0,150) . ' [...]';?> </p>
                    <a href="article.php?id=<?=$article['id'];?>">Lire la suite</a>
                </article>
            <?php // } ?>
            <?php endforeach; ?>
        </section>
    </main>
</body>
</html>